(require 'package)
(setq easy-hugo-basedir "/home/dylan/bookshelf/blog/")
(setq easy-hugo-url "https://ys2006.github.io")
(setq easy-hugo-sshdomain "github.com-ys2006")
(setq easy-hugo-root "~/blog")
(setq easy-hugo-previewtime "300")
(setq easy-hugo-default-ext ".org")
(define-key global-map (kbd "C-c C-e") 'easy-hugo)
(provide 'init-easy-hugo)
